AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Service Role'

Parameters:
  Contexto:
    Type: String
    Default: millennium-falcon
  PrivateSG:
    Type: String
  PrivateSubnetAZ1:
    Type: String
  PrivateSubnetAZ2:
    Type: String

Resources:

  eksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  eksServiceCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref Contexto
      RoleArn: !Ref eksServiceRole
      ResourcesVpcConfig:
        SecurityGroupIds:
        - !Ref PrivateSG
        SubnetIds:
        - !Ref PrivateSubnetAZ1
        - !Ref PrivateSubnetAZ2
         

Outputs:

  RoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt eksServiceRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RoleArn"