AWSTemplateFormatVersion: 2010-09-09
Parameters:
  PublicSubnet: 
    Type: String
  CIDRRange:
    Description: VPCCIDR Range (will be a /16 block)
    Type: String
    Default: 0.0.0.0/0
  PrivateRouteTable:
    Description: Enter Private Route Table ID.
    Type: String
  PrivateNetworkAcl:
    Description: Enter Public Network ACL ID.
    Type: String
  AllowNatRuleNumber:
    Description: Enter Public Network ACL Rule Number to Allow Return NAT Traffic.
    Type: Number
    Default: '120'

Resources:

  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC
      
  NatGateway:
    Type: AWS::EC2::NatGateway
    DependsOn: NatEIP
    Properties:
      AllocationId:
        Fn::GetAtt:
        - NatEIP
        - AllocationId
      SubnetId: !ImportValue publicSubnetId

  NatRoute:
    Type: AWS::EC2::Route
    DependsOn: NatGateway
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      DestinationCidrBlock: !Ref CIDRRange
      NatGatewayId: !Ref NatGateway

  InboundNetworkAclAllowNat:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: PrivateNetworkAcl
      RuleNumber:
        Ref: AllowNatRuleNumber
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: !Ref CIDRRange
      PortRange:
        From: '1024'
        To: '65535'

Outputs:
  NatGatewayId:
    Value:
      !Ref NatGateway
    Export:
      Name: NatGatewayId
  NatGatewayEIp:
    Value: !Ref NatEIP
    Export:
      Name: NatGatewayEIpId