AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to create Build Structure of docker application"

Parameters:

  appName:
    Type: String
    Default: millennium-falcon

Resources:

  codeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess

  containerRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Join ["-", ["ecr", !Ref appName]]

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Source:
        Type: GITHUB
        Location: https://github.com/lmanzieri/millennium-falcon.git
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                docker: 18
            pre_build:
              commands:
                - $(aws ecr get-login --no-include-email --region us-east-1)
            build:
              commands:
                - docker build -t millenium-falcon docker-app/.
            post_build:
              commands:
                - docker tag millenium-falcon:latest "${REPOSITORY_URI}/ecr-millennium-falcon:latest"
                - docker push "${REPOSITORY_URI}/ecr-millennium-falcon:latest"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/standard:2.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
      Name: !Join ['-',[!Ref appName, "buildproject"]]
      ServiceRole: !Ref codeBuildRole